-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: flake8
        args:
        - --ignore=E731, F841, H102, W504, H238, D104, E221